Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -34,18 +34,21 @@ jobs:
           go-version: "1.23"
 
       - name: Test
-        run: go test -coverprofile=coverage.out ./...
+        shell: bash
+        run: |
+          go test -coverpkg=./... ./... -v && go test ./... -coverprofile=cover.out ./... && go tool cover -func=cover.out
+
           coverage=$(go tool cover -func=coverage.out | awk '/total:/ {print $3}' | sed 's/%//' | awk '{print $1}')
           threshold=80
 
           if [[ -z "$coverage" ]]; then
-            echo "Error:Could not extract coverage percentage."
-            exit 1
+          echo "Error:Could not extract coverage percentage."
+          exit 1
           fi
 
           if (( $(echo "$coverage" ) < $threshold )); then
-            echo "Error:Coverage is below threshold ($coverage% < $threshold%)"
-            exit 1
+          echo "Error:Coverage is below threshold ($coverage% < $threshold%)"
+          exit 1
           else
-            echo "Coverage is $coverage%, which meets the threshold ($threshold%)"
+          echo "Coverage is $coverage%, which meets the threshold ($threshold%)"
           fi
